# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    prefer_single_quotes: false
    slash_for_doc_comments: false
    omit_local_variable_types: false
    unnecessary_new: false

analyzer:
#   exclude:
#     - path/to/excluded/files/**
