name: redpanda_light_client
description: redpanda - peer to peer chat, light client written in dart.
# version: 1.0.0
# homepage: https://redpanda.im
# author: robin <RobinFlohr@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

  buffer: ^1.0.6
  hex: ^0.1.2
  base58check: ^1.0.1
  byte_array: ^0.1.6
  pointycastle: ^1.0.2
  cryptography: ^0.1.2
  sentry: ">=3.0.0 <4.0.0"
