name: redpanda_light_client
description: redpanda - peer to peer chat, light client written in dart.
version: 0.0.1
homepage: https://redpanda.im

environment:
  sdk: '>=2.18.0-0 <3.0.0'

dependencies:
  buffer: ^1.0.6
  hex: ^0.2.0
  base58check: ^2.0.0
  byte_array: ^0.1.6
  pointycastle: ^3.3.0
  moor: ^4.3.1
  path: ^1.6.4
  asn1lib: ^1.0.2
  date_format: ^2.0.4
  logging: ^1.0.1
  sentry: ^6.1.2

dev_dependencies:
  test: ^1.14.3
  test_coverage:
    git:
      url: https://github.com/civts/test-coverage.git
      ref: aa6ffb41c28d7dec4e3bb11c3b7c4729e8271a69
  moor_generator: ^4.0.0-dev
  build_runner: ^2.1.1
  lints: ">=1.0.1 <3.0.0"
