name: redpanda_light_client
description: redpanda - peer to peer chat, light client written in dart.
version: 0.0.1
homepage: https://redpanda.im
author: Robin Braun <RobinFlohr@gmail.com>

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  buffer: ^1.0.6
  hex: ^0.2.0
  base58check: ^2.0.0
  byte_array: ^0.1.6
  pointycastle: ^3.3.0
  #  cryptography: ^0.1.2
  sentry: ^5.1.0
  flat_buffers: ^1.11.0
  moor: ^4.3.1
  #path_provider: ^1.6.5
  path: ^1.6.4
  asn1lib: ^1.0.2
  date_format: ^2.0.4
  logging: ^1.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.14.3
  #test_coverage: ^0.5.0
  moor_generator: ^4.0.0-dev
  build_runner: ^2.1.1