name: redpanda_light_client
description: redpanda - peer to peer chat, light client written in dart.
version: 0.0.1
homepage: https://redpanda.im
author: Robin Braun <RobinFlohr@gmail.com>

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  buffer: ^1.0.6
  hex: ^0.1.2
  base58check: ^1.0.1
  byte_array: ^0.1.6
  pointycastle: ^2.0.0
  #  cryptography: ^0.1.2
  sentry: ^4.0.1
  flat_buffers: ^1.11.0
  moor: ^3.4.0
  #path_provider: ^1.6.5
  path: ^1.6.4
  asn1lib: ^0.8.1
  date_format: ^1.0.8
  logging: ^0.11.4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.14.3
  test_coverage: ^0.4.1
  moor_generator: ^3.4.0
  build_runner: ^1.8.0